name: video_editor
version: 1.0.3
description: Video Editor allows trim, crop, rotate and scale video with a super flexible UI Design.
homepage: https://github.com/seel-channel/video_editor

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.0
  helpers: ^1.0.3
  video_player: ^1.0.1
  path_provider: ^1.6.27
  flutter_ffmpeg: ^0.3.1
  video_thumbnail: ^0.2.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
