name: video_editor
version: 1.1.0
description: Video Editor allows trim, crop, rotate and scale video with a super flexible UI Design.
homepage: https://github.com/seel-channel/video_editor

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.0
  video_player: ^2.1.0
  path_provider: ^2.0.1
  flutter_ffmpeg: ^0.4.0
  video_thumbnail: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
