name: video_editor
description: Video Editor allows trim, crop, rotate and scale video with a super flexible UI Design,
version: 1.0.0+1
homepage: https://github.com/seel-channel/video_editor

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.7.0
  helpers: ^1.0.1
  video_player: ^1.0.1
  path_provider: ^1.6.24
  flutter_ffmpeg: ^0.3.0
  video_thumbnail: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
